---
- name: Update apt and install dependencies
  apt:
    update_cache: yes

- name: Install python3 and pip
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3
    - python3-venv
    - python3-pip

- name: Add application user
  user:
    name: appuser
    shell: /bin/bash
    create_home: yes

- name: Create application directory
  file:
    path: /home/appuser/api
    state: directory
    owner: appuser
    group: appuser

- name: Copy application file
  copy:
    src: api.py
    dest: /home/appuser/api/api.py
    owner: appuser
    group: appuser

- name: Set up virtual environment
  become_user: appuser
  command: python3 -m venv /home/appuser/api/venv

- name: Install application dependencies
  become_user: appuser
  command: /home/appuser/api/venv/bin/pip install flask

- name: Create systemd service file
  template:
    src: api.service.j2
    dest: /etc/systemd/system/api.service

- name: Enable and start API service
  systemd:
    name: api
    enabled: yes
    state: started

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Configure Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify:
    - restart nginx
